version: 2.0
jobs:

  helloci:
    working_directory: ~/repo
    docker:
    - image: google/cloud-sdk:slim
    steps:
    - checkout
    - run:
        name: Say Hello
        command: |
          echo Hello Circle CI!


workflows:
  version: 2
  say-hello-to-ci:
    jobs:
    - helloci
